apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "emottak-event-manager"
  namespace: "team-emottak"
  labels:
    "team": "team-emottak"
spec:
  azure:
    application:
      enabled: true
  webproxy: true
  image: {{image}}
  startup:
    path: "/internal/health/liveness"
    port: 8080
    initialDelay: 600
    timeout: 30
    failureThreshold: 10
  liveness:
    path: "/internal/health/liveness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  readiness:
    path: "/internal/health/readiness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
        - id: "elastic-apm"
    logging:
      destinations:
        - id: elastic
        - id: loki
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: "1024Mi"
    requests:
      cpu: "300m"
      memory: "512Mi"
  ingresses:
    - "https://emottak-event-manager.intern.nav.no"
  vault:
    enabled: true
  kafka:
    pool: nav-prod
  accessPolicy:
    inbound:
      rules:
        - application: emottak-monitor
        - application: ebms-async
  env:
    - name: JDBC_URL
      value: jdbc:postgresql://A01DBVL009.adeo.no:5432/
    - name: DB_CREDENTIALS_MOUNT_PATH
      value: postgresql/prod-fss
    - name: ENABLE_EVENT_RECEIVER
      value: "true"
    - name: EMOTTAK_LOGGING_LEVEL
      value: DEBUG
